package:
  name: qca
  version: 8.2.1

source:
  #git_url: ssh://git@bitbucket.org/meznom/qca.git
  fn: meznom-qca-e02254a42ccb.tar.bz2
  url: https://bitbucket.org/meznom/qca/get/8.2.1.tar.bz2

requirements:
  build:
    - cmake
    - boost-headers
    - boost-python
    - boost-test
    - eigen
    - python
  run:
    - python
    - boost-python

build:
  number: 3

test:
  requires:
    - coma
    - numpy
    - ipython
    - pyzmq
    - matplotlib
  imports:
    - qca

about:
  home: https://bitbucket.org/meznom/qca
  license: BSD
  summary: An exact diagonalization implementation for quantum-dot cellular automata
